name: 'pipeline factory converter action'
description:
  'to convert the pipeline factory to github action that controlled by DevOps'
author: 'KBTG DevOps Team'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'
inputs:
  token:
    required: true
    description: 'Github token'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
